# Generated by Django 5.2.5 on 2025-10-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Order'),
        ),
    ]
